### ISSUE TITLE
DAP for LSP-jdtls

### ISSUE THREAD

**Issue by davidsoles** [sublimelsp/LSP-jdtls#24]
Sublime Text have some DAP that works with LSP-jdtls? If so, can you share some information?

Thanks... 👍🏼

**Comment by LDAP** [comment]
If refer to the debugger protocol, have a look here https://github.com/sublimelsp/LSP-jdtls/pull/7 and the corresponding PR on the Debugger repo.
The PR worked, however the experience was not that great. I think once LSP switches to Python 3.8 I will revisit this.

**Comment by LDAP** [comment]
[Sublime Debugger](https://github.com/daveleroy/sublime_debugger) now supports Java.
