### ISSUE TITLE
Debian Linux install Error

### ISSUE THREAD

**Issue by saharsadoghi** [sublimelsp/LSP-jdtls#32]
Hello
Debian Bullseye X64 with java 17 install error
--first installed LSP
--then LSP-jdtls
No config tweaked at any time.
at the end of LSP-jdtls I get  this:
![java](https://user-images.githubusercontent.com/119806946/205504736-9ce03014-6132-4c5f-b9b7-89e079d9e4db.jpg)

Please tell me how to diagnose this.
Thank You 0/

**Comment by LDAP** [comment]
Please follow the steps here
https://github.com/sublimelsp/LSP-jdtls/issues/31#issuecomment-1336365663 but open any Java project in step 8 and some Java file in this project in step 9.

Then open the command palette and execute LSP: Troubleshoot Server and select jdtls.

**Comment by saharsadoghi** [comment]
the @LDAP answer fixed the problem minus using the `--safe-mode` switch. just do all of that but don't use `--safe-mode` just open regular sublime.
thak you @LDAP  🌷🏵️
