### ISSUE TITLE
Work Done Progress leads to `unknown $/progress token` ST console log entries

### ISSUE THREAD

**Issue by LDAP** [sublimelsp/LSP-jdtls#37]
**Describe the bug**
ST console is flooded with `LSP: unknown $/progress token: <token>` when servers report [Work Done Progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress).

[lsp-log.txt](https://github.com/sublimelsp/LSP/files/10253802/lsp-log.txt)

[st-log.txt](https://github.com/sublimelsp/LSP/files/10253803/st-log.txt)

**To Reproduce**
1. Start LSP-jdtls
2. Check ST console

**Expected behavior**
Nothing is logged to console

**Screenshots**
_none_

**Environment (please complete the following information):**
- Sublime Text version: 4145
- LSP version: https://github.com/sublimelsp/LSP/commit/9c82ccd217c379de98a439166cceaaafc9282e38
- LSP-jdtls version: https://github.com/sublimelsp/LSP-jdtls/commit/c1301059d08a6a8d838bc0623ef208444a7cbed2

**Additional context**
_none_

**Comment by rwols** [comment]
To be fair, now that I'm reading that section again it mentions

> To keep the protocol backwards compatible 

But does that mean we didn't have `window/workDoneProgress/create` before? In any case, it's been a few years now that there's `window/workDoneProgress/create`.

**Comment by LDAP** [comment]
I assumed `$/progress` with kind `begin` is enough to start progress reporting because of this section:

>[Work Done Progress Begin](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin)
To start progress reporting a [$/progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgressBegin) notification with the following payload must be sent:

It seems like VSCode and the Vim client both support missing `window/workDoneProgress/create` requests.

**Comment by jwortmann** [comment]
> To be fair, now that I'm reading that section again it mentions
> 
> > To keep the protocol backwards compatible
> 
> But does that mean we didn't have `window/workDoneProgress/create` before? In any case, it's been a few years now that there's `window/workDoneProgress/create`.

I don't think this is the case, and the relevant part of the specs is right at the beginning of that section https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#initiatingWorkDoneProgress

> Work Done progress can be initiated in two different ways:
> 1. [...]
> 2.  by a server using the request `window/workDoneProgress/create`. The document will refer to this kind of progress as server initiated progress.

Note that the link is to the 3.15 version of the specs when "Work Done Progress" was introduced, i.e. this request was always part of it.

**Comment by LDAP** [comment]
A workaround was implemented in LSP package.
