### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'java'

### ISSUE THREAD

**Issue by ilmoralito** [sublimelsp/LSP-jdtls#39]
Sublime 4113
Ubuntu 22.04.1
java version 17.0.3-tem

When opening a `.java` file I am receiving the following error message:

`Unable to start subprocess for jdtls`
`FileNotFoundError: [Errno 2] No such file or directory: 'java'`

In order to fix I try

LSP-jdtls settings
```
{
    "java.home": "/home/mario/.sdkman/candidates/java/current"
}
```

But the error message doesn't go away. 

I installed java using sdkman. Greetings in advance

**Comment by rchl** [comment]
I don't know much about this server but I know that your setting is invalid. The `java.home` should be inside a `settings` object. Look at default settings and replicate the same structure.

**Comment by ilmoralito** [comment]
Thanks for answering. My mistake. I haven't noticed

This setup works as expected

```
{
    "settings": {
        "java.home": "/home/username/.sdkman/candidates/java/current"
    },
}
```
