### ISSUE TITLE
Problem with setup for Spring Boot Java

### ISSUE THREAD

**Issue by astokum** [sublimelsp/LSP-jdtls#41]
I am trying to build a spring boot project in Sublime text 4. But Sublime shows error and warning ⚠️ that specific package that is belongs to springbootframework is not found...

I can say it is `javac` linting problem. Because of i will have didn't provide a classpath of spring boot framework lib. 
But i have tried to do on my way. Till now i am getting error and warning.

```Any solution for that? Plz...```

**Comment by LDAP** [comment]
Can you share a minimal example? I used jdtls for spring boot in the past and it worked just fine.

**Comment by astokum** [comment]
Ok , I will share a screenshot to you.
