### ISSUE TITLE
Failed to start JDTLS : HTTP Error 404 Not Found | exit code -1

### ISSUE THREAD

**Issue by blackjyn** [sublimelsp/LSP-jdtls#45]
Just happened. 

![image](https://github.com/sublimelsp/LSP-jdtls/assets/6046191/e309095e-179a-4105-b4de-fd23558706b6)

when I try to test serve:r 
![image](https://github.com/sublimelsp/LSP-jdtls/assets/6046191/499253a5-88da-4178-9e62-f296ed608aaa)

I try to clear JDTLS data and re install the LSP JDTLS package but no luck.

**Comment by LDAP** [comment]
Fixed by https://github.com/sublimelsp/LSP-jdtls/commit/6d2b08dde03adf452e69fe5fa900a0e14de879ba.
Should land on Package Control in a few hours.

**Comment by blackjyn** [comment]
Thanks 👍
