### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by rchl** [sublimelsp/LSP-jdtls#46]
I'm doing some refactoring in LSP and I was wondering why this code opens files after applying workspace edits. Doesn't `apply_parsed_workspace_edits` already opened them all?

https://github.com/sublimelsp/LSP-jdtls/blob/303f47bbf270f5df4251830a6b5c334659de4055/modules/test_extension_commands.py#L57-L66

**Comment by LDAP** [comment]
I don't remember the reason. Might just be an overlook on my side?
I'm busy until the end of January, I can take a closer look at it afterward.

**Comment by predragnikolic** [comment]
also I would add this from the boot.py file.
```
def reload_plugin():
    import sys

    for m in list(sys.modules.keys()):
        if m.startswith(__package__ + ".") and m != __name__:
            del sys.modules[m]


reload_plugin()
```

**Comment by rchl** [comment]
What do you mean by that?
Are you suggesting that it should be removed and if so, why?

**Comment by predragnikolic** [comment]
I would suggest to remove it.

When I saw that peace of code code I asked myself why was it added in the first place... My initial guess is to reload the plugin after it has been updated.

I do not think that plugins should add logic to reload themselves. For me, it looks like something to be improved in Package Control, rather then each plugging optionally adding code like this.

**Comment by rchl** [comment]
it might be to mostly cater for local development but it's up to @LDAP to decide :)

**Comment by LDAP** [comment]
The reloading code is primarily for local development. Therefore I would like to keep it in.

**Comment by rchl** [comment]
Ok to close since we've determined that it's needed
