### ISSUE TITLE
Enquiry?

### ISSUE THREAD

**Issue by london-coder** [sublimelsp/LSP-jdtls#48]
Hi Rafal,
First, many thanks to you for your work to make this Sublime Text plugin (package) available. It's much appreciated :-)

I see you recently updated it to include the 1.28.0 release of the eclipse-jdtls, that added support for Java 21. Thank you. Since then (September 2023), there have been later releases, the latest is 1.30.0.  I appreciate you will be busy, but, could I ask how often you look to update this package?

Kind regards,
Alan

**Comment by LDAP** [comment]
It's on my todo for next week.

**Comment by rchl** [comment]
@LDAP is the main maintainer and the man to thank :)

**Comment by london-coder** [comment]
My apologies to @LDAP 
Thank you Lucas 😃 . Your efforts are much appreciated.

**Comment by LDAP** [comment]
I updated JDTLS to 1.27.1 just now. Further updates require additional work, since Microsoft does not publish `.vsix` files on GitHub anymore, which contain the compiled debug/test plugin assets.

**Comment by london-coder** [comment]
Hi @LDAP

Excuse my ignorance, but what is the relationship between Visual Studio Extension Installer (.vsix), and the Eclipse language server for sublime text?  
Thanks Lucas

**Comment by LDAP** [comment]
JDTLS is extended using plugins, the vsix packages the compiled files. Without the vsix files this package would have to download and compile the source of the plugins, which is considerably more work and error-prone than unpacking a file.
