### ISSUE TITLE
Plugin dont work with Build 4173 

### ISSUE THREAD

**Issue by Viterzgir** [sublimelsp/LSP-jdtls#50]
Recently i upgraded to Sublime Text Build 4173 and i don't see caption jdtls on the left bottom and autocompletion  don't work anymore. Trying to clear data and reload lsp server in project it's not show jdtls.  Sublime Text Build 4172 works fine.

**Comment by rwols** [comment]
FYI you don't have to downgrade ST anymore, a fix has been released.
