### ISSUE TITLE
Failing with Java 22 (Unsupported class file major version 66)

### ISSUE THREAD

**Issue by soychpapalus** [sublimelsp/LSP-jdtls#51]
``` 1 !SESSION 2024-04-26 18:46:03.633 -----------------------------------------------
  2 eclipse.buildId=unknown
  3 java.version=22
  4 java.vendor=N/A
  5 BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
  6 Command-line arguments:  -data /home/xxxx/.cache/sublime-text/Package Storage/LSP-jdtls/data
  7
  8 !ENTRY org.apache.aries.spifly.dynamic.bundle 4 0 2024-04-26 18:46:04.236
  9 !MESSAGE FrameworkEvent ERROR
 10 !STACK 0
 11 java.lang.IllegalArgumentException: Unsupported class file major version 66```

Steps I took:

1. Installed LSP package
2. Installed LSP-jdtls package

**Comment by soychpapalus** [comment]
Fixed it by following the following guide (with edits): https://lsp.readthedocs.io/en/stable/#java

Comments:
* My installation is on Linux
* I downloaded and extracted Eclipse's `jdt-ls` to `/.local/share/eclipse-jdt-server/`
* The recommended settings were added to `LSP-jdtls.sublime-settings` (with edits)
* The line `"PATH/TO/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_*.jar"` was edited to `~/.local/share/eclipse-jdt-server/plugins/org.eclipse.equinox.launcher_1.6.800.v20240330-1250.jar` (the version you use might change... For me it did not work with the wildcard in the filename
* `"-noverify"` was removed
* `"<TEMP_DIR>/${project_base_name}/jdt_ws"` replaced with `"/tmp/${project_base_name}/jdt_ws"`

**Comment by palexdev** [comment]
This plugin is broken
The only way I got java working is to follwo the above instructions

**Comment by LDAP** [comment]
I need more info to fix this for everyone. LSP-jdtls version, LSP version, ST version, Windows/Mac/Linux? Also run the troubleshoot server command from the ST command panel.

**Comment by palexdev** [comment]
> I need more info to fix this for everyone. LSP-jdtls version, LSP version, ST version, Windows/Mac/Linux? Also run the troubleshoot server command from the ST command panel.

Just now I tried to reproduce the issue but everything is working. I think 2627751 fixed it
