### ISSUE TITLE
Java code formatting

### ISSUE THREAD

**Issue by amadeuscam** [sublimelsp/LSP-jdtls#55]
Hello everyone! 
I put this lines in the config, but it doesn't seem to work
  "java.format.settings.profile": "GoogleStyle",
   "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",

**Comment by LDAP** [comment]
Is there something in the LSP log panel or ST console?

**Comment by amadeuscam** [comment]
After searching the internet, I saw that you have to put the xml in the project and put the path relative to it, now it works for me

**Comment by LDAP** [comment]
Glad you could resolve your issue :)
